
find_package(PkgConfig REQUIRED)

pkg_check_modules(PKG_WAYLAND_CLIENT QUIET wayland-client)
pkg_check_modules(PKG_WAYLAND_SERVER QUIET wayland-server)

pkg_check_modules(PKG_WAYLAND_EGL QUIET wayland-egl)
pkg_check_modules(PKG_WAYLAND_CURSOR QUIET wayland-cursor)

find_path(WAYLAND_CLIENT_INCLUDE_DIRS
    NAMES wayland-client.h
    HINTS ${PKG_WAYLAND_CLIENT_INCLUDE_DIRS}
)
find_path(WAYLAND_SERVER_INCLUDE_DIRS
    NAMES wayland-server.h
    HINTS ${PKG_WAYLAND_SERVER_INCLUDE_DIRS}
)

find_path(WAYLAND_EGL_INCLUDE_DIRS
    NAMES wayland-egl.h
    HINTS ${PKG_WAYLAND_EGL_INCLUDE_DIRS}
)
find_path(WAYLAND_CURSOR_INCLUDE_DIRS
    NAMES wayland-cursor.h
    HINTS ${PKG_WAYLAND_CURSOR_INCLUDE_DIRS}
)


find_library(WAYLAND_CLIENT_LIBRARIES
    NAMES wayland-client
    HINTS ${PKG_WAYLAND_CLIENT_LIBRARY_DIRS}
)
find_library(WAYLAND_SERVER_LIBRARIES
    NAMES wayland-server
    HINTS ${PKG_WAYLAND_SERVER_LIBRARY_DIRS}
)

find_library(WAYLAND_EGL_LIBRARIES
    NAMES wayland-egl
    HINTS ${PKG_WAYLAND_EGL_LIBRARY_DIRS}
)
find_library(WAYLAND_CURSOR_LIBRARIES
    NAMES wayland-cursor
    HINTS ${PKG_WAYLAND_CURSOR_LIBRARY_DIRS}
)

if(PKG_WAYLAND_CLIENT_FOUND)
    set(WAYLAND_CLIENT_FOUND TRUE)

    set(WAYLAND_CLIENT_CFLAGS ${PKG_WAYLAND_CLIENT_CFLAGS})
    set(WAYLAND_CLIENT_CFLAGS_OTHER ${PKG_WAYLAND_CLIENT_CFLAGS_OTHER})

    set(WAYLAND_CLIENT_LDFLAGS ${PKG_WAYLAND_CLIENT_LDFLAGS})
    set(WAYLAND_CLIENT_LDFLAGS_OTHER ${PKG_WAYLAND_CLIENT_LDFLAGS_OTHER})
endif()
if(PKG_WAYLAND_SERVER_FOUND)
    set(WAYLAND_SERVER_FOUND TRUE)

    set(WAYLAND_SERVER_CFLAGS ${PKG_WAYLAND_SERVER_CFLAGS})
    set(WAYLAND_SERVER_CFLAGS_OTHER ${PKG_WAYLAND_SERVER_CFLAGS_OTHER})

    set(WAYLAND_SERVER_LDFLAGS ${PKG_WAYLAND_SERVER_LDFLAGS})
    set(WAYLAND_SERVER_LDFLAGS_OTHER ${PKG_WAYLAND_SERVER_LDFLAGS_OTHER})
endif()

if(PKG_WAYLAND_EGL_FOUND)
    set(WAYLAND_EGL_FOUND TRUE)

    set(WAYLAND_EGL_CFLAGS ${PKG_WAYLAND_EGL_CFLAGS})
    set(WAYLAND_EGL_CFLAGS_OTHER ${PKG_WAYLAND_EGL_CFLAGS_OTHER})

    set(WAYLAND_EGL_LDFLAGS ${PKG_WAYLAND_EGL_LDFLAGS})
    set(WAYLAND_EGL_LDFLAGS_OTHER ${PKG_WAYLAND_EGL_LDFLAGS_OTHER})
endif()
if(PKG_WAYLAND_CURSOR_FOUND)
    set(WAYLAND_CURSOR_FOUND TRUE)

    set(WAYLAND_CURSOR_CFLAGS ${PKG_WAYLAND_CURSOR_CFLAGS})
    set(WAYLAND_CURSOR_CFLAGS_OTHER ${PKG_WAYLAND_CURSOR_CFLAGS_OTHER})

    set(WAYLAND_CURSOR_LDFLAGS ${PKG_WAYLAND_CURSOR_LDFLAGS})
    set(WAYLAND_CURSOR_LDFLAGS_OTHER ${PKG_WAYLAND_CURSOR_LDFLAGS_OTHER})
endif()

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(WAYLAND DEFAULT_MSG
    WAYLAND_CLIENT_INCLUDE_DIRS WAYLAND_CLIENT_LIBRARIES
    WAYLAND_SERVER_INCLUDE_DIRS WAYLAND_SERVER_LIBRARIES

    WAYLAND_EGL_INCLUDE_DIRS WAYLAND_EGL_LIBRARIES
    WAYLAND_CURSOR_INCLUDE_DIRS WAYLAND_CURSOR_LIBRARIES
)